version: '2.1'
services:
    postgres:
        image: postgres:9.6
        container_name: "airflow_db"
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
    webserver:
        image: puckel/docker-airflow:1.10.1
        container_name: "airflow_webserver"
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
        volumes:
            - "./dags:/usr/local/airflow/dags"
            - "./requirements/requirements.txt:/requirements.txt"
            - "/Users/robinchampseix/Desktop/stage/aura/data_aura/todo/:/usr/local/airflow/todo/:rw"
            - "/Users/robinchampseix/Desktop/stage/aura/data_aura/write_complete/:/usr/local/airflow/write_complete/:rw"
            - "/Users/robinchampseix/Desktop/stage/aura/data_aura/problem_files/:/usr/local/airflow/problem_files/:rw"
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8081:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

#networks:
#  default:
#    external:
#      name: "{{ aura_docker_network }}"
